### ISSUE TITLE
Conection error?

### ISSUE THREAD

**Issue by Nosh-Ware** [CITGuru/tempmail#5]
I seem to be getting this error:
` Traceback (most recent call last):
  File "C:\Users\Nosh\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\urllib3\connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "C:\Users\Nosh\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\urllib3\util\connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Nosh\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\urllib3\connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\Nosh\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\urllib3\connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "C:\Users\Nosh\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\urllib3\connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "C:\Users\Nosh\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\urllib3\connection.py", line 353, in connect
    conn = self._new_conn()
  File "C:\Users\Nosh\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\urllib3\connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x0000023627E7FDF0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Nosh\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "C:\Users\Nosh\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\urllib3\connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "C:\Users\Nosh\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\urllib3\util\retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='privatix-temp-mail-v1.p.mashape.com', port=443): Max retries exceeded with url: /request/domains/format/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000023627E7FDF0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Nosh\Desktop\TempEmailMaker.py", line 4, in <module>
    email = tm.get_email_address()  # v5gwnrnk7f@gnail.pw
  File "C:\Users\Nosh\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\tempMail2.py", line 70, in get_email_address
    available_domains = self.available_domains
  File "C:\Users\Nosh\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\tempMail2.py", line 36, in available_domains
    req = requests.get(url, headers={
  File "C:\Users\Nosh\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\requests\api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\Nosh\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\Nosh\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Nosh\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\Nosh\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='privatix-temp-mail-v1.p.mashape.com', port=443): Max retries exceeded with url: /request/domains/format/json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000023627E7FDF0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')) `

I have executed the code directly form the readme, fixing the syntax for python 3. What is going wrong?

**Comment by Nosh-Ware** [comment]
I have reviewed that my rapid api key is valid and working with other apis in python.

**Comment by gitricko** [comment]
yeah, same problem for me

**Comment by Nosh-Ware** [comment]
I made a pr for documentation of some things I figured. Guess this is a dead repo. :_(

**Comment by basicterminal** [comment]
This is because the API of this is incorrect, they changed it.

It is now: `privatix-temp-mail-v1.p.rapidapi.com`

**Comment by ghltshubh** [comment]
> This is because the API of this is incorrect, they changed it.
> 
> It is now: `privatix-temp-mail-v1.p.rapidapi.com`

Throws: `Failed to resolve 'privatix-temp-mail-v1.p.mashape.com'`

**Comment by ghltshubh** [comment]
> This is because the API of this is incorrect, they changed it.
> 
> It is now: `privatix-temp-mail-v1.p.rapidapi.com`

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/project/lib/python3.10/site-packages/tempMail2.py", line 72, in get_email_address
    self.domain = random.choice(available_domains)
  File "/project/lib/python3.10/random.py", line 378, in choice
    return seq[self._randbelow(len(seq))]
KeyError: 0
```
